import React, { useMemo, useState } from 'react';
import {
  ArrowUpRight,
  Calendar,
  CheckCircle2,
  Download,
  Info,
  LineChart,
  Percent,
  RotateCcw,
  SlidersHorizontal,
  Sparkles,
  TrendingDown,
  TrendingUp,
} from 'lucide-react';
import { ProcessedSalesProject } from '../../types';
import { ChartDataPoint, InteractiveChart } from '../charts/InteractiveChart';
import { formatCompactCurrency, formatCurrency } from '../../utils/timeSeriesEngine';

interface FutureForecastViewProps {
  project: ProcessedSalesProject;
  onNavigateTab: (tab: any) => void;
}

export const FutureForecastView: React.FC<FutureForecastViewProps> = ({ project, onNavigateTab }) => {
  const { monthlyData, futureForecast, selectedModelOrder } = project;
  const { records, totalSales, averageMonthlySales, highestMonth, lowestMonth } = futureForecast;

  // Scenario Simulator State
  const [growthAdjustment, setGrowthAdjustment] = useState<number>(0); // -30 to +30%
  const [scenarioMode, setScenarioMode] = useState<'baseline' | 'expansion' | 'conservative' | 'custom'>('baseline');

  const applyScenario = (mode: 'baseline' | 'expansion' | 'conservative' | 'custom', pct: number) => {
    setScenarioMode(mode);
    setGrowthAdjustment(pct);
  };

  // Adjusted records based on scenario
  const simulatedRecords = useMemo(() => {
    const factor = 1 + growthAdjustment / 100;
    return records.map((r, idx) => {
      // Compounded adjustment over 12 months or flat multiplier
      const stepFactor = 1 + (growthAdjustment / 100) * ((idx + 1) / 12);
      const adjForecast = Number((r.forecastSales * stepFactor).toFixed(2));
      const adjLower = Number(Math.max(0, r.lower95CI * stepFactor).toFixed(2));
      const adjUpper = Number((r.upper95CI * stepFactor).toFixed(2));
      return {
        ...r,
        forecastSales: adjForecast,
        lower95CI: adjLower,
        upper95CI: adjUpper,
      };
    });
  }, [records, growthAdjustment]);

  // Simulated aggregates
  const simForecast1M = simulatedRecords[0]?.forecastSales || 0;
  const simForecast3M = simulatedRecords.slice(0, 3).reduce((a, b) => a + b.forecastSales, 0);
  const simForecast6M = simulatedRecords.slice(0, 6).reduce((a, b) => a + b.forecastSales, 0);
  const simForecast12M = simulatedRecords.reduce((a, b) => a + b.forecastSales, 0);
  const simAverageMonthly = simForecast12M / simulatedRecords.length;
  const simHighest = [...simulatedRecords].sort((a, b) => b.forecastSales - a.forecastSales)[0];
  const simLowest = [...simulatedRecords].sort((a, b) => a.forecastSales - b.forecastSales)[0];

  // Chart data: full historical actuals + forward 12-month projections
  const futureChartData: ChartDataPoint[] = useMemo(() => {
    const list: ChartDataPoint[] = [];

    // Historical actuals
    monthlyData.forEach((m, idx) => {
      list.push({
        label: m.monthLabel,
        subLabel: 'Historical Actual',
        actual: m.sales,
        isSplitPoint: idx === monthlyData.length - 1,
      });
    });

    // 12-Month Future Forecast
    simulatedRecords.forEach((f) => {
      list.push({
        label: f.monthLabel,
        subLabel: scenarioMode === 'baseline' ? 'ARIMA Projection' : `Scenario (${growthAdjustment > 0 ? '+' : ''}${growthAdjustment}%)`,
        forecast: f.forecastSales,
        lowerCI: f.lower95CI,
        upperCI: f.upper95CI,
      });
    });

    return list;
  }, [monthlyData, simulatedRecords, scenarioMode, growthAdjustment]);

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-[#E2E8F0] pb-4">
        <div>
          <h2 className="text-xl font-bold tracking-tight text-[#0F172A]">12-Month Future Sales Forecast</h2>
          <p className="text-xs text-[#64748B] mt-0.5">
            Forward-looking projections generated by refitting ARIMA({selectedModelOrder.join(',')}) on complete historical dataset
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={() => onNavigateTab('forecast-table')}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-[#CBD5E1] bg-white text-xs font-medium text-[#475569] hover:bg-[#F1F5F9] hover:text-[#0F172A] transition-colors shadow-xs"
          >
            <span>View Full Table</span>
          </button>
        </div>
      </div>

      {/* Interactive What-If Scenario Simulator Toolbar */}
      <div className="rounded-xl border border-[#E2E8F0] bg-white p-4 space-y-3 shadow-xs">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div className="flex items-center gap-2">
            <SlidersHorizontal className="h-4 w-4 text-[#2563EB]" />
            <h3 className="text-xs font-bold text-[#0F172A] uppercase tracking-wider">
              Executive What-If Scenario Simulator
            </h3>
            {growthAdjustment !== 0 && (
              <span className={`text-[11px] font-mono px-2 py-0.5 rounded font-bold ${growthAdjustment > 0 ? 'bg-[#F0FDF4] text-[#15803D] border border-[#BBF7D0]' : 'bg-[#FEF2F2] text-[#B91C1C] border border-[#FECACA]'}`}>
                {growthAdjustment > 0 ? '+' : ''}{growthAdjustment}% Shift
              </span>
            )}
          </div>

          {/* Quick Preset Buttons */}
          <div className="flex items-center gap-1.5 text-xs">
            <button
              onClick={() => applyScenario('baseline', 0)}
              className={`px-2.5 py-1 rounded font-medium transition-colors ${
                scenarioMode === 'baseline' ? 'bg-[#2563EB] text-white shadow-xs' : 'bg-[#F1F5F9] text-[#475569] hover:text-[#0F172A]'
              }`}
            >
              Baseline ARIMA
            </button>
            <button
              onClick={() => applyScenario('expansion', 15)}
              className={`px-2.5 py-1 rounded font-medium transition-colors ${
                scenarioMode === 'expansion' ? 'bg-[#16A34A] text-white shadow-xs' : 'bg-[#F1F5F9] text-[#475569] hover:text-[#0F172A]'
              }`}
            >
              Expansion (+15%)
            </button>
            <button
              onClick={() => applyScenario('conservative', -15)}
              className={`px-2.5 py-1 rounded font-medium transition-colors ${
                scenarioMode === 'conservative' ? 'bg-[#DC2626] text-white shadow-xs' : 'bg-[#F1F5F9] text-[#475569] hover:text-[#0F172A]'
              }`}
            >
              Recession (-15%)
            </button>
            {growthAdjustment !== 0 && (
              <button
                onClick={() => applyScenario('baseline', 0)}
                className="p-1 rounded bg-[#F1F5F9] text-[#64748B] hover:text-[#0F172A] border border-[#E2E8F0]"
                title="Reset to baseline"
              >
                <RotateCcw className="h-3.5 w-3.5" />
              </button>
            )}
          </div>
        </div>

        {/* Fine-Tuning Slider */}
        <div className="flex items-center gap-4 pt-1">
          <span className="text-[11px] font-mono text-[#64748B] shrink-0">-30%</span>
          <input
            type="range"
            min="-30"
            max="30"
            step="1"
            value={growthAdjustment}
            onChange={(e) => {
              setGrowthAdjustment(parseInt(e.target.value, 10));
              setScenarioMode('custom');
            }}
            className="w-full accent-[#2563EB] cursor-pointer h-1.5 bg-[#E2E8F0] rounded-lg appearance-none"
          />
          <span className="text-[11px] font-mono text-[#64748B] shrink-0">+30%</span>
          <span className="text-xs font-mono font-bold text-[#0F172A] shrink-0 w-14 text-right">
            {growthAdjustment > 0 ? '+' : ''}{growthAdjustment}%
          </span>
        </div>
      </div>

      {/* Forecast Cumulative Horizon Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="rounded-xl border border-[#E2E8F0] bg-white p-5 space-y-2 shadow-xs">
          <div className="flex items-center justify-between text-xs text-[#64748B]">
            <span className="font-semibold uppercase tracking-wider">Next Month Forecast</span>
            <span className="font-mono text-[#2563EB] text-[11px] font-bold">{simulatedRecords[0]?.monthLabel}</span>
          </div>
          <p className="text-2xl font-bold font-mono text-[#0F172A] tabular-nums">
            {formatCurrency(simForecast1M)}
          </p>
          <p className="text-xs text-[#64748B] leading-snug">
            Immediate short-term projection with narrowest confidence band.
          </p>
        </div>

        <div className="rounded-xl border border-[#E2E8F0] bg-white p-5 space-y-2 shadow-xs">
          <div className="flex items-center justify-between text-xs text-[#64748B]">
            <span className="font-semibold uppercase tracking-wider">3-Month Cumulative</span>
            <span className="font-mono text-[#0284C7] text-[11px] font-bold">Quarterly Horizon</span>
          </div>
          <p className="text-2xl font-bold font-mono text-[#0F172A] tabular-nums">
            {formatCompactCurrency(simForecast3M)}
          </p>
          <p className="text-xs text-[#64748B] leading-snug">
            Avg {formatCurrency(simForecast3M / 3)} per month over the next 90 days.
          </p>
        </div>

        <div className="rounded-xl border border-[#E2E8F0] bg-white p-5 space-y-2 shadow-xs">
          <div className="flex items-center justify-between text-xs text-[#64748B]">
            <span className="font-semibold uppercase tracking-wider">6-Month Cumulative</span>
            <span className="font-mono text-[#7C3AED] text-[11px] font-bold">H1 Outlook</span>
          </div>
          <p className="text-2xl font-bold font-mono text-[#0F172A] tabular-nums">
            {formatCompactCurrency(simForecast6M)}
          </p>
          <p className="text-xs text-[#64748B] leading-snug">
            Avg {formatCurrency(simForecast6M / 6)} per month for medium-term budgeting.
          </p>
        </div>

        <div className="rounded-xl border border-[#E2E8F0] bg-white p-5 space-y-2 shadow-xs">
          <div className="flex items-center justify-between text-xs text-[#64748B]">
            <span className="font-semibold uppercase tracking-wider">12-Month Total Sales</span>
            <span className="font-mono text-[#16A34A] text-[11px] font-bold">Full Annual</span>
          </div>
          <p className="text-2xl font-bold font-mono text-[#16A34A] tabular-nums">
            {formatCompactCurrency(simForecast12M)}
          </p>
          <p className="text-xs text-[#64748B] leading-snug">
            Expected total business volume for upcoming fiscal year.
          </p>
        </div>
      </div>

      {/* Main Historical + 12-Month Forecast Visual */}
      <InteractiveChart
        title={scenarioMode === 'baseline' ? 'Historical Actuals & 12-Month ARIMA Forward Forecast' : `Scenario Simulation: ${growthAdjustment > 0 ? '+' : ''}${growthAdjustment}% Forward Projection`}
        subtitle="Historical observations (blue) transitioning across forecast boundary into forward predictions (coral dashed) with expanding 95% confidence intervals"
        data={futureChartData}
        splitLabel="Forecast Horizon Start"
        height={390}
        showMovingAverage={false}
        showConfidenceInterval={true}
      />

      {/* Peak & Trough Summary Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="rounded-xl border border-[#E2E8F0] bg-white p-4 flex items-center justify-between shadow-xs">
          <div>
            <span className="text-xs text-[#64748B] uppercase tracking-wider block font-semibold">
              Projected Peak Revenue Month
            </span>
            <span className="text-lg font-bold font-mono text-[#15803D] mt-1 block">
              {formatCurrency(simHighest.forecastSales)}
            </span>
            <span className="text-xs text-[#64748B] font-sans">{simHighest.monthLabel}</span>
          </div>
          <div className="h-10 w-10 rounded-lg bg-[#F0FDF4] border border-[#BBF7D0] flex items-center justify-center text-[#16A34A]">
            <ArrowUpRight className="h-5 w-5" />
          </div>
        </div>

        <div className="rounded-xl border border-[#E2E8F0] bg-white p-4 flex items-center justify-between shadow-xs">
          <div>
            <span className="text-xs text-[#64748B] uppercase tracking-wider block font-semibold">
              Projected Trough Month
            </span>
            <span className="text-lg font-bold font-mono text-[#D97706] mt-1 block">
              {formatCurrency(simLowest.forecastSales)}
            </span>
            <span className="text-xs text-[#64748B] font-sans">{simLowest.monthLabel}</span>
          </div>
          <div className="h-10 w-10 rounded-lg bg-[#FFFBEB] border border-[#FDE68A] flex items-center justify-center text-[#D97706]">
            <Calendar className="h-5 w-5" />
          </div>
        </div>

        <div className="rounded-xl border border-[#E2E8F0] bg-white p-4 flex items-center justify-between shadow-xs">
          <div>
            <span className="text-xs text-[#64748B] uppercase tracking-wider block font-semibold">
              Average Monthly Forecast
            </span>
            <span className="text-lg font-bold font-mono text-[#2563EB] mt-1 block">
              {formatCurrency(simAverageMonthly)}
            </span>
            <span className="text-xs text-[#64748B] font-sans">Across 12 Future Months</span>
          </div>
          <div className="h-10 w-10 rounded-lg bg-[#EFF6FF] border border-[#BFDBFE] flex items-center justify-center text-[#2563EB]">
            <Sparkles className="h-5 w-5" />
          </div>
        </div>
      </div>

      {/* Safety & Methodological Notice */}
      <div className="rounded-xl border border-[#E2E8F0] bg-[#F8FAFC] p-4 text-xs text-[#475569] flex items-start gap-3">
        <Info className="h-4 w-4 text-[#2563EB] shrink-0 mt-0.5" />
        <div className="space-y-1">
          <span className="font-semibold text-[#0F172A]">Forecasting Methodology & Safety:</span>
          <p className="leading-relaxed">
            All future projections are explicitly labeled as model forecasts with expanding 95% confidence interval boundaries. Confidence interval widths expand with horizon length <code className="font-mono text-[#1D4ED8] bg-[#EFF6FF] px-1 py-0.5 rounded">h</code> as cumulative shock variance compounds.
          </p>
        </div>
      </div>
    </div>
  );
};
